### ISSUE TITLE
Remove exchanges that no longer list MSR

### ISSUE THREAD

**Issue by soullesscomputerboy** [masari-project/masari-project.github.io#10]
I believe bisq removed MSR as I cannot find a trading pair on the website, or the app itself. If there is a way to add MSR to the list, I think there should be a how-to under the link.

Leaving Citex on the list of exchanges may create confusion/fear for new users of Masari. There is potential that some people may just search Citex and start using the exchange. Masari is also no longer listed there. Since it is a confirmed scam, it should just be removed from this list.

**Comment by camthegeek** [comment]
We are supported on Bisq but inactive as far as I know. It would be better to completely remove Bisq from our website so no one is chasing a ghost.

Regarding Citex, I agree with you. It should be removed. I'll update the exchanges page shortly!

**Comment by camthegeek** [comment]
This is taken care of now in the following commits:
- https://github.com/masari-project/masari-project.github.io/commit/22b8508fd96bec8b75fd53dae7afc1e493b2727b
- https://github.com/masari-project/masari-project.github.io/commit/bf63a9fe19e8d5dbbf819cd32e159b187db2fedc
